dest_postgres:
  host:     
  port:                        
  database:               
  user:                     
  connect_timeout: 10

streams:
  - kafka_topic: 
    consumer_group: 
    dest_table: <schema>.<table_name>
    commit_batch_size: 100           
    auto_create_table: true          

kafka:
  bootstrap_servers: kafka:9092    
  consumer:
    auto_offset_reset: earliest
    enable_auto_commit: false        
    session_timeout_ms: 30000
    max_poll_interval_ms: 300000