-- Run as ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- Databases (environment separation)
CREATE DATABASE RAW     COMMENT = 'Landing zone for all ingested data';
CREATE DATABASE STAGING COMMENT = 'dbt staging/intermediate models';
CREATE DATABASE PROD    COMMENT = 'Production analytics models';
CREATE DATABASE DEV     COMMENT = 'Developer sandbox';

-- Warehouses (size per workload)
CREATE WAREHOUSE COMPUTE_WH    WAREHOUSE_SIZE='SMALL'  AUTO_SUSPEND=300  AUTO_RESUME=TRUE;
CREATE WAREHOUSE LOADING_WH    WAREHOUSE_SIZE='SMALL'  AUTO_SUSPEND=60   AUTO_RESUME=TRUE;
CREATE WAREHOUSE REPORTING_WH  WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60   AUTO_RESUME=TRUE;

-- Roles (least-privilege)
CREATE ROLE LOADER;      -- Airflow extraction jobs
CREATE ROLE TRANSFORMER; -- dbt models
CREATE ROLE REPORTER;    -- BI tools (read-only)
CREATE ROLE DEVELOPER;   -- Engineers in dev DB

-- Grants
GRANT USAGE ON WAREHOUSE LOADING_WH   TO ROLE LOADER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH   TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE REPORTING_WH TO ROLE REPORTER;

GRANT ALL ON DATABASE RAW     TO ROLE LOADER;
GRANT ALL ON DATABASE RAW     TO ROLE TRANSFORMER;
GRANT ALL ON DATABASE STAGING TO ROLE TRANSFORMER;
GRANT ALL ON DATABASE PROD    TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN DATABASE PROD TO ROLE REPORTER;

-- Service accounts
CREATE USER dbt_user    PASSWORD='...' DEFAULT_ROLE=TRANSFORMER MUST_CHANGE_PASSWORD=FALSE;
CREATE USER airflow_user PASSWORD='...' DEFAULT_ROLE=LOADER     MUST_CHANGE_PASSWORD=FALSE;

GRANT ROLE TRANSFORMER TO USER dbt_user;
GRANT ROLE LOADER      TO USER airflow_user;